### ISSUE TITLE
Reports error in parent template instead of partial

### ISSUE THREAD

**Issue by westonganger** [slm-lang/slm#10]
I am using partials in my template.

The error I was getting says: `dashboard_3/slm/index.slm, Line 35, Column 13`

It reports an error on such and such line of the parent template file name. 
It should say the partial's file name instead because the error was in the partial on that line and column.
Ex. `dashboard_3/slm/partials/nav.slm, Line 35, Column 13`

**Comment by yury** [comment]
Can you create test sample, so I can make unit test around that?

Thank you.
