### ISSUE TITLE
coffee: tag support

### ISSUE THREAD

**Issue by ozjd** [slm-lang/slm#13]
At present, there's no [Coffeescript](http://coffeescript.org/) support in _Slm_. As a workaround, I've added [Using Coffeescript in Slm (with ExpressJS)](https://github.com/slm-lang/slm/wiki/Using-Coffeescript-in-Slm-(with-ExpressJS)) to the Wiki.

What are your thoughts on a `coffee:` tag; not dissimilar to the one in *Slim*?

I'm happy to contribute, as long as that is not against the proposed direction of this project.

**Comment by yury** [comment]
Thank you for wiki page.

We want to keep `slm` core clean and tiny as possible :)

So, I propose to create `slm-coffee` node module as [slm-markdown](https://github.com/slm-lang/slm-markdown) and we will add it to https://github.com/slm-lang

What do you think?

Also, I'm not very good in english... So help we tutorials, docs is very welcomed :)

**Comment by ozjd** [comment]
It doesn't sound bad at all, let me take a look at it later on :+1:

**Comment by ozjd** [comment]
Update: [slm-coffee](https://github.com/ozjd/slm-coffee).

**Comment by yury** [comment]
@ozjd I have invited you to slm-lang org. Can you move repo there?

**Comment by ozjd** [comment]
@yury I've accepted, but you'll need to adjust the permissions

    You don’t appear to have permission to create repositories for this organization. Sorry about that.

**Comment by yury** [comment]
@ozjd Ok, I think we have two options :)

1. I will create slm-coffee and add you there as owner. But you have to push there your commits
2. You will add me as owner to your repo, so I would be able to move it to org

what do you think?

**Comment by ozjd** [comment]
Fork it for now, then I'll fix it up after you've done that :-)

**Comment by ozjd** [comment]
Sorry about that - the close  button is in a really bad place on my phone.

If you fork `ozjd/slm-coffee` into slm-lang, and then I'll delete it (which makes slm-lang the owner) and then I'll fork back into my Github.

**Comment by yury** [comment]
@ozjd done!

**Comment by ozjd** [comment]
All done! I'll close this issue for now. Thanks 😀
