### ISSUE TITLE
Boolean Attributes

### ISSUE THREAD

**Issue by ozjd** [slm-lang/slm#14]
Currently, if `attribute=false` it's swallowed up (as expected) but `attribute=true` returns `attribute=""`.

Wouldn't it make more sense that if `attribute=true` that it just returns `attribute`

I notice that there's an Issue (or 10) over on Siml (started by @yury). There were some talks about incompatibility with XHTML, but an XHTML dev would surely use `attribute=""` etc.

I'm started with `doctype 5` but this doesn't seem to make a difference.
Is this intended behaviour? is there reasoning behind it?

**Comment by yury** [comment]
Thank you for issue.

Will look at weekend.

**Comment by yury** [comment]
So, actually it managed by Engine `format` option (`xml`, `xhtml` or `html`). Default it `xhtml`. I exposed that option to Template. But still thinking how to better integrate it with `__express`.

**Comment by ozjd** [comment]
There's not really a great way to expose options to express that I know of, I might have to look at the source.

The other thought I had was setting that option with the `doctype` - eg. We know `doctype 5` is going to be a HTML doctype.

**Comment by yury** [comment]
@ozjd  thank you.

**Comment by sintro** [comment]
For some reason I still get `attribute=""` even when I type `doctype html` or `doctype 5` at the top of slim file. Is not this directive should explicitly set format to `html`?
