### ISSUE TITLE
Render 'for' doesn't work

### ISSUE THREAD

**Issue by MichaelDanilov** [slm-lang/slm#25]
I've added the test for `for`:

```js
lab.test('render with for', function(done) {
    assertHtml(template, [
      'ul',
      '  - for item in this.items',
      '    li = item.item',
      ],
      '<ul><li>test1</li><li>test2</li></ul>',
      {items:[{item:'test1'},{item:'test2'}]}, done);
  });
```
and see this:
`expected '<ul><li></li><li></li><li></li></ul>' to deeply equal '<ul><li>test1</li><li>test2</li></ul>'`

**Comment by yury** [comment]
Hi @MichaelDanilov.

`assertHtml` function has `options` as it fourth parameter (not context).
Instead, `assertHtml` defines it's own context with `items: [0, 1, 3]`. So that is why your test is fail.

Sorry for late response.
