### ISSUE TITLE
How to output object data in script?

### ISSUE THREAD

**Issue by PanMan** [slm-lang/slm#31]
I have tried many variations to get an object from the Node side to the Slim side of things.
But the template doesn't (server-side) execute code within script tags.
Basically, what I want to end up with:
````
<script>
var scores={this is my object from the node side of things}
</script>
````

If I do e.g.
````
span = JSON.stringify(this.scores)
````
it works and prints the object

However, no version of 
````
script var scores = JSON.stringify(this.scores)
````
works, as (I think) as soon as its within a script, slim assumes this is client side, and doesn't execute the code server side? Right?
How do I work around this?

**Comment by yury** [comment]
```
javascript:
  window.data.user = ${=j(this.user)};
```

**Comment by PanMan** [comment]
W00t, thanks a lot! I'll do a PR for the docs.

**Comment by yury** [comment]
That would be awesome!

**Comment by PanMan** [comment]
Done in https://github.com/slm-lang/slm/pull/32
