### ISSUE TITLE
orign html error!

### ISSUE THREAD

**Issue by ginus** [slm-lang/slm#4]
slm:
```
<script>
 var a=b;
</script>
```
will be html:
```
<script><script>
```
my code dispeared!
I think any in orign tag pairs should be keep.

**Comment by ginus** [comment]
my love livescript+stylus+slm

**Comment by yury** [comment]
I will look at this issue. But you can use embedded script for now
```
script:
  var a=b;
```

**Comment by yury** [comment]
actually, your code should be 
```
<script>
  | var a=b;
</script>
```

**Comment by yury** [comment]
But I recommend you to use `script:`
