### ISSUE TITLE
Doesn't work with VueJS attribute syntax.

### ISSUE THREAD

**Issue by alexandremagro** [slm-lang/slm#43]
Something like this:

`form @submit.prevent="createProject"`

Throws `Error: Text line not indented deep enough.`

or

`form(@submit.prevent="createProject")`

Throws `Error: Expected attribute`

Non-shorthand syntax, like `form v-on:submit="something"`, also does not work.
This syntax was not a problem in Slim, I've been migrating my project from Sprockets (Rails) to Webpack and I had this problem.

**Comment by shilov** [comment]
+1 ran into this as well

**Comment by yury** [comment]
Fixed in 1.0.0 version

**Comment by shilov** [comment]
Spasibo!
