### ISSUE TITLE
Partials, caching?

### ISSUE THREAD

**Issue by bradgreens** [slm-lang/slm#5]
Hi team. I've been trying out `slm` with `gulp-slm` and some live reload tools. I'm seeing a problem where editing partials does not recompile with the updated HTML. I've put together a test project here - https://github.com/bradgreens/github-test-gulp-slm-partials.

When I make edits to https://github.com/bradgreens/github-test-gulp-slm-partials/blob/master/slm/partials/_header.slm, they appear on the first page load using the gulp stack. 

When I make additional edits, I can see the entire `gulp-watch` system kick off and the `gulp-slim` code execute (via console logs), and `gulp-livereload` reload the browser. But after all of this the new partial HTML does not render out. If I restart gulp and re-save the main template `test.slm` I can get the changes to work.

It seems to me that the partial `.slm` code is getting cached or isn't seeing my changes after the first rendering.

When I make changes to the parent template, `test.slm` the changes do work with the full stack and I see the updates live in the browser, the problem seems specific to the included partial templates. Thanks in advance for any help.

**Comment by simnalamburt** [comment]
:+1:

**Comment by yury** [comment]
Yep, you have to disable caching for live reload. See [PR](https://github.com/bradgreens/github-test-gulp-slm-partials/pull/1)

**Comment by bradgreens** [comment]
Tested and worked. Thanks!
