### ISSUE TITLE
I can't seem to get hapi view helpers working with slm

### ISSUE THREAD

**Issue by jasoncypret** [slm-lang/slm#7]
```
server.views({
  engines: {
    'slm': Slm
  },
  path: './views',
  helpersPath: './app/helpers',
  compileOptions: {
    basePath: __dirname + '/views',
    useCache: false
  },
  context: defaultContext,
  isCached: false
})
```

Are helpers supported in SLM?

https://github.com/hapijs/hapi/issues/1592

**Comment by DmitryTsepelev** [comment]
@jasoncypret as far as I know hapi view helpers work with handlebars only

**Comment by yury** [comment]
@jasoncypret You can `require` your helpers in templates. Or define them on pre render on context.

**Comment by yury** [comment]
Closing this issue for now.

**Comment by jasoncypret** [comment]
Thanks @yury! Just now circling back. I ended up adding some helpers to the `onPreResponse`. Working perfect. Cheers!

**Comment by yury** [comment]
@jasoncypret I'm glad you like it. Any thoughts on improvement? (except docs :)

**Comment by lastobelus** [comment]
I'm a hapi newbie and I wanted to use slm in my first project, but use a standard syntax for helpers. This works (with no attempt to implement block helpers), but I worry I may be doing something dumb performance-wise. Is there a clean way to only actually load a helper if it is used?

```javascript
server.ext('onPreResponse', function loadHelpers(request, reply) {
  var response = request.response;

  if (response.variety === 'view') {
    var context = response.source.context;
    console.log("in onPreResponse: context:",context);
    var helpers = require('require-all')({
      dirname: __dirname + '/helpers',
      resolve: function(helper) {
        var helper_context = {
          name: 'name_from_query',
          hash: {},
          data: {
            root: context
          }
        };
        return helper.bind(null, helper_context);
      }
    });
    Hoek.merge(context, helpers);
    return reply.continue();
  }
  return reply.continue();
});
```

**Comment by lastobelus** [comment]
Also, in handlebars the context object also has a `name` attr set to the name of the helper, but require-all doesn't pass the name to  `resolve`  for some reason.

**Comment by lastobelus** [comment]
I actually spoke to soon. The above works for jade, but not slm. :(

**Comment by jcbize** [comment]
@lastobelus: How did the solution above end up working out for you?

**Comment by lastobelus** [comment]
@jcbize The project was cancelled and I haven't had an occasion to use Hapi again. But, it did seem to work in development at least.

**Comment by jcbize** [comment]
Oh, interesting. Thanks for following up!

In case others run into this same issue using Hapi, this has been working well for me:

`const viewHelpers = RequireAll(__dirname + '/views/helpers');
  server.ext('onPreResponse', function(request, reply) {
    if (request.response.variety === 'view') {
      Hoek.merge(request.response.source.context, viewHelpers);
    }
    return reply.continue();
  });
`
